# Caption one-hot encoding

In [1]:
import numpy as np

In [2]:
completed_captions = np.load(r'C:\Users\Νίκος Λιθαρής\Desktop\med-image-captioning\data\padded_captions\padded_captions.npy') #completed means that the captios are tokenized and padded


In [3]:
print(completed_captions.shape) # Example batch with 100 images

(100, 178)


In [4]:
#Craate the targets
targets=np.zeros(completed_captions.shape,dtype=int)
targets[:,:-1]=completed_captions[:,1:]

In [5]:
print(targets)

[[   5  567  568 ...    0    0    0]
 [ 586  587    1 ...    0    0    0]
 [ 624   47   53 ...    0    0    0]
 ...
 [  55   48    9 ...    0    0    0]
 [  75   25  528 ...    0    0    0]
 [  78 1952    7 ...    0    0    0]]


In [6]:
np.save(r'C:\Users\Νίκος Λιθαρής\Desktop\med-image-captioning\data\targets\targets.npy',targets) #save the targets