In [2]:
import pandas as pd
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences
from keras.utils import to_categorical

C:\Users\Νίκος Λιθαρής\AppData\Local\Temp\ipykernel_11332\3277340313.py:1: DeprecationWarning: 
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466
        
  import pandas as pd


## Load the data

In [3]:
def load_captions(filename):
    df=pd.read_csv(filename,header=0)

    captions=df[df.columns[0]].values
    return captions

In [4]:
captions=load_captions(r'D:\med-image-captioning\captions\image_uri_and_captions_100_cleaned.csv')
print('Loaded %d captions' % len(captions))

Loaded 100 captions


In [5]:
print(captions[0])

uld ct false negative example 47yo male with 15 years of asbestos exposure subtle posterior basal interstitial abnormalities related to early asbestosis are visible instandard acquisition adlp of 201mgycm but indiscernible onuld ct bdlp of 19mgycm


## Prepare tokenizer

In [6]:
tokenizer=Tokenizer()
tokenizer.fit_on_texts(captions)
vocab_size=len(tokenizer.word_index)+1
print('Vocabulary size: %d' % vocab_size)

Vocabulary size: 1978


## Integer encoding

In [7]:
sequences=tokenizer.texts_to_sequences(captions)

In [12]:
print(sequences[0])

[566, 5, 567, 568, 569, 570, 137, 3, 301, 302, 1, 571, 303, 572, 304, 102, 573, 574, 575, 8, 305, 576, 14, 138, 577, 578, 579, 1, 580, 64, 581, 582, 5, 583, 1, 584]


## Padding sequences

In [8]:
max_length=max(len(s) for s in sequences)
print('Max caption length: %d' % max_length)
padded=pad_sequences(sequences,maxlen=max_length,padding='post')


Max caption length: 178


In [13]:
print(padded[0])

[566   5 567 568 569 570 137   3 301 302   1 571 303 572 304 102 573 574
 575   8 305 576  14 138 577 578 579   1 580  64 581 582   5 583   1 584
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]


## One-hot encoding

In [9]:
y=to_categorical(padded,num_classes=vocab_size)
y=y.reshape((len(padded),max_length,vocab_size))
print('Padded shape: %s' % str(padded.shape))


Padded shape: (100, 178)


In [14]:
print(y[0])

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]]


In [11]:
# # save y to a pkl file
# import pickle
# with open(r'D:\med-image-captioning\data\caption_features\caption_features.pkl','wb') as f:
#     pickle.dump(y,f)